ASONMODE: "&aOn"
ASOFFMODE: "&cOff"
StartUpDelay: 10
MinUpdateDelay: 250
Scoreboard:
  Title: "&aScoreboard"
  Items:
    - "This is your"
    - "example scoreboard"
    - "With placeholderapi"
    - "&c&lsupport!"